title: 'Gradient Accents '
description: Where movies come together
github_repo: Preacher-6
github_username: GradientAccent
social_link: 'https://twitter.com/'
social_username: PreacherSix
theme_color: black
remote_theme: broccolini/swiss
remote_theme_layouts:
  - default
  - page
  - post
  - home
